# This is the network config written by 'subiquity'
network:
  bonds:
    bond0:
      addresses:
      - 10.101.9.11/26
      interfaces:
      - ens20f0np0
      - ens20f1np1
      nameservers:
        addresses: []
        search: []
      parameters:
        lacp-rate: slow
        mode: 802.3ad
        transmit-hash-policy: layer3+4
      routes:
      - to: default
        via: 10.101.9.1
  ethernets:
    ens20f0np0: {}
    ens20f1np1: {}
  version: 2
