#!/bin/bash
set -euo pipefail

RULE_FILE="/etc/udev/rules.d/70-persistent-net.rules"
TARGET_NICS=(ens11np0 ens13np0 ens15np0 ens17np0)

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

echo '# This file is autogenerated. Do not edit manually.' > "$tmp"

for nic in "${TARGET_NICS[@]}"; do
    if [[ ! -d "/sys/class/net/$nic" ]]; then
        echo "skip: $nic not present"
        continue
    fi

    mac="$(cat "/sys/class/net/$nic/address")"

    cat >> "$tmp" <<EOF
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="$mac", ATTR{type}=="1", NAME="$nic"
EOF

    echo "added rule: $mac -> $nic"
done

install -m 0644 "$tmp" "$RULE_FILE"
udevadm control --reload-rules

echo "written: $RULE_FILE"
echo "NOTE: rules reloaded only. do NOT run udevadm trigger on remote hosts."
echo "reboot in maintenance window to verify names stay unchanged."
